export const estados: Estado[] = [
  { estado: '', UF: '' },
  { estado: 'Acre', UF: 'AC', ibge: 12 },
  { estado: 'Alagoas', UF: 'AL', ibge: 27 },
  { estado: 'Amazonas', UF: 'AM', ibge: 13 },
  { estado: 'Amapá', UF: 'AP', ibge: 16 },
  { estado: 'Bahia', UF: 'BA', ibge: 29 },
  { estado: 'Ceará', UF: 'CE', ibge: 23 },
  { estado: 'Distrito Federal', UF: 'DF', ibge: 53 },
  { estado: 'Espirito Santo', UF: 'ES', ibge: 32 },
  { estado: 'Goiás', UF: 'GO', ibge: 52 },
  { estado: 'Maranhão', UF: 'MA', ibge: 21 },
  { estado: 'Minas Gerais', UF: 'MG', ibge: 31 },
  { estado: 'Mato Grosso do Sul', UF: 'MS', ibge: 50 },
  { estado: 'Mato Grosso', UF: 'MT', ibge: 51 },
  { estado: 'Pará', UF: 'PA', ibge: 15 },
  { estado: 'Paraíba', UF: 'PB', ibge: 25 },
  { estado: 'Pernambuco', UF: 'PE', ibge: 26 },
  { estado: 'Piauí', UF: 'PI', ibge: 22 },
  { estado: 'Paraná', UF: 'PR', ibge: 41 },
  { estado: 'Rio de janeiro', UF: 'RJ', ibge: 33 },
  { estado: 'Rio Grande do Norte', UF: 'RN', ibge: 24 },
  { estado: 'Rondônia', UF: 'RO', ibge: 11 },
  { estado: 'Roraima', UF: 'RR', ibge: 14 },
  { estado: 'Rio Grande do Sul', UF: 'RS', ibge: 43 },
  { estado: 'Santa Catarina', UF: 'SC', ibge: 42 },
  { estado: 'Sergipe', UF: 'SE', ibge: 28 },
  { estado: 'São Paulo', UF: 'SP', ibge: 35 },
  { estado: 'Tocantins', UF: 'TO', ibge: 17 },
]
